### ISSUE TITLE
one command for PR flow?

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#41]
I just realised that it's now 4 commands we should run for each new sheet in a PR:

- sourcelookup
- fixhg
- updatefeatures
- describe

Yes, for some (fixhg for non-HG etc) nothing will happen, but it's probably a good habit to just run all of them. 

I've informed the coders now about updatefeatures being run on sheets not assigned to someone. They might request that the sheet they're working on is completed, but regardless by the time it makes it in for PR it's probably good to run updatefeatures.

Would it be possible to roll all of these into one command alongside the separate ones? Something like "PRevaluation"

Possible one could also roll in:

- remove_empty
- cleanmojibake
- recode
- fix (I'm not entirely sure what fix does but it seems useful)

**Comment by xrotwang** [comment]
I think it makes sense to keep the commands separate, because often things reported earlier on in the workflow require intervention. Also, things like `fixhg` are only required for a subset of PRs.

**Comment by HedvigS** [comment]
Okay. I was thinking that having one command for all might just simplify, and not let to one of us miss running one. fixhg on non HG-sheets just does nothing right?

**Comment by xrotwang** [comment]
fixhg always runs on the whole repository - so may have effects in other sheets. Also, the commands have very different performance characteristics. I'd always want to run `grambank describe` first, because it's just a lot quicker than sourcelookup. And often enough it turns up issues that need fixing before running sourcelookup makes sense at all.

**Comment by HedvigS** [comment]
Fair enough.
