### ISSUE TITLE
speeding up sourcelookup?

### ISSUE THREAD

**Issue by HedvigS** [grambank/pygrambank#70]
I suspect that the function sourcelookup in pygrambank is slowed down by going through all of hh.bib and gb.bib.

Is there a function we can have that loads these two in a simple format in the python environment so that it doesn't need to take so long every time?

**Comment by xrotwang** [comment]
Caching such things introduces
- another layer of complexity
- another potential source for confusion
- and one of the [two hard things in computer science](https://martinfowler.com/bliki/TwoHardThings.html).

Also, code doing caching is really difficult to test.

So, I'd rather not do that, because I think it's quite a task if done properly.

**Comment by HedvigS** [comment]
Okay.

In that case, could sourcelookup please accept more than one sheet at a time so I can set it to report on a set of sheets and go do something else and then check back after a good while?

**Comment by HedvigS** [comment]
I'd like this to work please

` grambank --repos /Users/skirgard/Git/Glottobank/Grambank sourcelookup /Users/skirgard/Git/glottolog/glottolog "original_sheets/JE_alun1238.tsv, original_sheets/JE_ford1242.tsv" `

**Comment by HedvigS** [comment]
or that I can give it a txt files with the file paths on a new row, that'd be even sweeter.
